# Site settings
title: Suraj
header-img: img/home-bg.jpg
email: surajsharma121@gmail.com
description: "My journey in the tech world."
baseurl: ""
url: "surajs21.github.io"
twitter_username: surajsharma121
github_username:  surajwy
facebook_username:  surajs21

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
static_version: 1